
import { Inter } from "next/font/google"
import Head from "next/head"
import React, { useState } from 'react';
import Swal from 'sweetalert2'
import withReactContent from "sweetalert2-react-content";


// const inter = Inter({ subsets: ["latin"] })



export default function Home() {

  const [connected, setConnected] = useState<boolean>(false);
  const [valid, setValid] = useState<boolean>(false);
  
  function connect(){
    setConnected(!connected);
    var isValid = false;
    setValid(isValid);
    if(!connected && !isValid){
      showSwal();
    }
  }

  const showSwal = () => {
    withReactContent(Swal).fire({
      title: "Something missing",
      text: "Be sure your wallet had a transition to Uniswap in the last 24h",
      showConfirmButton: false,
      icon: "error",
    })
  }

  return (
    <>
      <Head>
        <title>Check Uniswap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/uni.ico" />
      </Head>
      <main>
        <h1 className="title"><span className="accent">Uniswap</span> Check </h1>
        <div className="row">
          {/* {isMobile &&
            <> 
              <div className="col-6">
                <text className="subtitle">Connetti il wallet e riscatta il tuo NFT di benvenuto*!</text>
                <text className="condition"> *Se hai effettuato una transazione su uniswap nelle ultime 24h</text>
              </div>
              <div className="col-6">
                <button className="btn btn-primary"> Connect </button>
                <button className="btn btn-nft"> Get Your NFT </button>
              </div>
            </>
          } */}
          
            <div className="col-12">
              <text className="subtitle">Connect your wallet and retrieve your welcome NFT!</text>
              <text className="condition">Be sure your wallet had a transition to Uniswap in the last 24h</text>
              
              
              <button className="btn btn-connect" onClick={() => connect()}> <strong>{connected ? "disconnect" : "connect wallet"}</strong> </button>
              <button className="btn btn-nft" disabled={!connected || connected && !valid}><strong> mint your NFT </strong></button>
            </div>
        </div>
      </main>
    </>
  )
}
